### ISSUE TITLE
"Browser Position"オプションを変更すると例外が発生する

### ISSUE THREAD

**Issue by fkfk** [nobuhito/atom-web-search#5]
毎度すみません。
設定から"Browser Position"オプションを変更すると例外が発生するようです。
発生時のスタックトレースをお送りします。

```
/C:/Users/XXXXX/.atom/packages/web-search/lib/web-search.coffee:117
Hide Stack Trace
TypeError: Cannot read property 'destroy' of null
    at Object.module.exports.WebSearch.browserPanelRefresh (file:///C:/Users/XXXXX/.atom/packages/web-search/lib/web-search.coffee:75:18)
    at file:///C:/Users/XXXXX/.atom/packages/web-search/lib/web-search.coffee:42:67
    at D:\opt\Atom\resources\app.asar\src\config.js:623:20
    at Function.module.exports.Emitter.simpleDispatch (D:\opt\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\opt\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (D:\opt\Atom\resources\app.asar\src\config.js:808:29)
    at Config.module.exports.Config.setRawValue (D:\opt\Atom\resources\app.asar\src\config.js:600:19)
    at Config.module.exports.Config.set (D:\opt\Atom\resources\app.asar\src\config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (D:\opt\Atom\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:196:28)
    at HTMLSelectElement.<anonymous> (D:\opt\Atom\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:210:26)
    at HTMLSelectElement.jQuery.event.dispatch (D:\opt\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLSelectElement.elemData.handle (D:\opt\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by nobuhito** [comment]
@fkfk Atom1.4のバグ？でセッティング周りがおかしくなっているようです。

ref. https://github.com/atom/atom/issues/10426

先ほどパッチを当ててみましたので最新バージョンで試していただけますでしょうか？

**Comment by fkfk** [comment]
@nobuhito 早期のご対応ありがとうございます。
v0.3.1で例外が出ないことを確認できました。
